# config/server.yaml
# Server (hostname: Media) — machine profile configuration.

disk:
  disk_by_id: nvme-SAMSUNG_MZVLB256HBHQ-000L2_S4DXNF1MC92121
  boot_part: -part1
  root_part: -part2

root:
  mode: reuse
  subvolumes:
    - name: "@pkg"
      reuse: yes
    - name: "@home"
      reuse: no
    - name: "@local_aur_repo"
      mount: /srv/local-aur-repo
      reuse: yes
    - name: "@tailscale"
      mount: /var/lib/tailscale
      reuse: yes

additional_mounts:
  - name: personal
    disk_by_id: nvme-WD_PC_SN740_SDDPTQD-1T00_230802800561
    type: ssd
    part: -part2
    mountpoint: /mnt/Personal
  - name: containers
    disk_by_id: nvme-SAMSUNG_MZVLB256HBHQ-000L2_S4DXNF1MC92121
    type: ssd
    part: -part3
    mountpoint: /mnt/containers
  - name: ironwolf
    disk_by_id: ata-ST2000DM006-2DM164_Z4Z974PW
    type: hdd
    part: -part1
    mountpoint: /mnt/IronWolf
  - name: valkyrie
    disk_by_id: ata-WDC_WD60EFAX-68JH4N0_WD-WX42D10HZKUJ
    type: hdd
    part:
    mountpoint: /mnt/Valkyrie

bind_mounts:
  - source: /mnt/Valkyrie/Movies
    target: /mnt/containers/media/Movies
  - source: /mnt/IronWolf/Movies
    target: /mnt/containers/media/Movies2
  - source: /mnt/Valkyrie/Series
    target: /mnt/containers/media/Series
  - source: /mnt/IronWolf/Series
    target: /mnt/containers/media/Series2

system:
  hostname: Media
  autologin: true

boot:
  bootloader: none
  init: dracut

pkgprofile:
  post: []

machine_specific:
  pacman:
    - filezilla
  aur:
    - libation

features:
  local_aur_repo:
    server:
      enabled: true

  reflector:
    enabled: true

  firewall:
    enabled: true

  zram:
    enabled: false

  plymouth:
    enabled: false

  tailscale:
    enabled: true
    config:
      auto_up: true

  pia:
    enabled: false

  snapper:
    enabled: false

  ssh:
    enabled: true

  claude_code:
    enabled: false

  antigravity:
    enabled: false

  btrfs_maintenance:
    enabled: true

  ananicy:
    enabled: true

postconfig:
  user_dirs:
    enabled: true

  dotfiles:
    enabled: true

  bluetooth:
    enabled: false

  gnome:
    gsettings:
      enabled: true

    lockscreen_scaling:
      enabled: false

    keybindings:
      enabled: false

    color_profiles:
      enabled: false

    theme:
      icons:
        enabled: false
      cursor:
        enabled: true
      wallpapers:
        enabled: false

    extensions:
      enabled: true
      ids: []

    appdrawer:
      enabled: true
      dock:
        - filezilla
      layout:
        - # page 1
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.clocks
          - org.gnome.Papers
          - Libation
          - System
          - Utilities
          - org.gnome.Showtime
          - org.gnome.Weather
