#!/bin/bash

#Check Internet Connection
scripts/./check_internet || exit 1

pushd scripts

# Early Configs
./con_home_shortcuts
./con_etc_settings

# Packages Installation
./pkg_pacman
./pkg_paru
./pkg_batch
./pkg_pia
./pkg_plymouth
./pkg_snapper

# Late Configs
./con_dconf
./con_pacman_hooks

# App Drawer
./con_appdrawer

popd
