#!/bin/bash

#Check Internet Connection
iwctl station wlan0 connect Ansible
scripts/./check_internet || exit 1

source install.cfg
pushd scripts

# Reformat vs Refresh based on user questions
read -p "Do you want $ArchPart reformatted?(y/n)" F_ROOT
if [ "$F_ROOT" = "y" ]; then
	./btrfs_subvolume $ArchPart $ArchLabel
else
	read -p "Do you want Home formatted?(y/n)" F_HOME
	read -p "Do you want Pkg formatted?(y/n)" F_PKG
	./btrfs_refresh $ArchPart $F_HOME $F_PKG; 
fi

# Mount all partitions
./mount_tree $MountPath $ArchPart $EfiPart $MountOpsSsd $ArchLabel $SwapPart

# Pacstrap
./ins_pacstrap $MountPath

# Fstab generate and add Personal mount
./ins_fstab $MountPath $PersonalPart

# Chrooting
./ins_chroot $MountPath $HostName $TimeZone

# Intalling gnome and drivers
./ins_drivers_gnome $MountPath

# Install Grub Bootloader
./bl_grub $MountPath 

popd
