# config/desktop_core.yaml
# Desktop (hostname: Titan) — disk, mounts, system, and boot.

disk:
  disk_by_id: nvme-Sabrent_Rocket_4.0_1TB_03F1079B0E4400624890
  boot_part: -part1
  root_part: -part3

root:
  mode: reuse
  subvolumes:
    - name: "@pkg"
      reuse: yes
    - name: "@home"
      reuse: no

additional_mounts:
  - name: personal
    disk_by_id: nvme-Sabrent_Rocket_4.0_1TB_03F1079B0E4400624890
    type: ssd
    part: -part2
    mountpoint: /mnt/Personal

system:
  hostname: Titan

boot:
  bootloader: refind
  init: mkinitcpio
