# config/server_config.yaml
# Server — post-install configuration overrides.

postconfig:

  user_dirs:
    enabled: true

  dotfiles:
    enabled: true

  bluetooth:
    enabled: false

  gnome:
    gsettings:
      enabled: true

    lockscreen_scaling:
      enabled: false

    keybindings:
      enabled: false

    color_profiles:
      enabled: false

    theme:
      icons:
        enabled: false
      cursor:
        enabled: true
      wallpapers:
        enabled: false

    extensions:
      enabled: true
      ids: []

    appdrawer:
      enabled: true
      dock:
        - filezilla 
      layout:
        - # page 1
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.clocks
          - org.gnome.Papers
          - Libation
          - System
          - Utilities
          - org.gnome.Showtime
          - org.gnome.Weather
          
