#!/bin/bash

MountPath=$1

arch-chroot $MountPath pacman -S grub os-prober --noconfirm
arch-chroot $MountPath grub-install --target=x86_64-efi --efi-directory=/efi --bootloader-id=GRUB
sed -i 's/#GRUB_DISABLE_OS_PROBER=false/GRUB_DISABLE_OS_PROBER=false/' $MountPath/etc/default/grub
arch-chroot $MountPath grub-mkconfig -o /boot/grub/grub.cfg
