#!/bin/bash

# Dconf Editor
gsettings set ca.desrt.dconf-editor.Settings show-warning false
gsettings set ca.desrt.dconf-editor.Settings restore-view false

# Desktop
#gsettings set org.gnome.desktop.background picture-uri 'file:///home/ajay/Pictures/WP Simple.jpg'
#gsettings set org.gnome.desktop.background picture-uri-dark 'file:///home/ajay/Pictures/WP Simple.jpg'
gsettings set org.gnome.desktop.datetime automatic-timezone true

gsettings set org.gnome.desktop.interface clock-format '12h'
gsettings set org.gnome.desktop.interface clock-show-date true
gsettings set org.gnome.desktop.interface font-name 'Inter 13'
gsettings set org.gnome.desktop.interface document-font-name 'Inter 13'
gsettings set org.gnome.desktop.interface monospace-font-name 'JetBrainsMonoNL Nerd Font Mono 13'
gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'
gsettings set org.gnome.desktop.interface font-hinting 'full'
gsettings set org.gnome.desktop.interface text-scaling-factor 1.15
#gsettings set org.gnome.desktop.interface gtk-theme 'Adapta-Nokto'
#gsettings set org.gnome.desktop.interface cursor-theme 'Paper'
#gsettings set org.gnome.desktop.interface icon-theme 'Paper'

gsettings set org.gnome.desktop.media-handling autorun-never true

gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true  
gsettings set org.gnome.desktop.peripherals.touchpad speed 0.75  

gsettings set org.gnome.desktop.privacy old-files-age 3
gsettings set org.gnome.desktop.privacy recent-files-max-age 7
gsettings set org.gnome.desktop.privacy remove-old-temp-files true
gsettings set org.gnome.desktop.privacy remove-old-trash-files true


# Document Viewer
gsettings set org.gnome.Evince.Default continuous false
gsettings set org.gnome.Evince.Default dual-page true
gsettings set org.gnome.Evince.Default sizing-mode 'fit-page'

# Others
gsettings set org.gnome.SimpleScan jpeg-quality '90'
gsettings set org.gnome.SimpleScan save-format 'image/jpeg'
gsettings set org.gnome.system.location enabled true
gsettings set org.gnome.tweaks show-extentions-notice false
gsettings set org.gnome.TextEditor restore-session false

# File Chooser
gsettings set org.gtk.gtk4.Settings.FileChooser sort-directories-first false
gsettings set org.gtk.Settings.FileChooser clock-format '12h'

# Key Bindings
export PATH="${PATH}:/home/ajay/Arch/Scripts"
Keybinds_Gnome.pl -i ~/Arch/Config/keybindings.csv
