#!/bin/bash

# Eyecandy
#paru -S starship ttf-jetbrains-mono-nerd fzf zoxide #oh-my-posh 

## Multimedia
paru -S amberol eartag

# Webapps
paru -S webapp-manager

# Citrix
paru -S icaclient
mkdir -p $HOME/.ICAClient/cache
cp /opt/Citrix/ICAClient/config/{All_Regions,Trusted_Region,Unknown_Region,canonicalization,regions}.ini $HOME/.ICAClient/


