#!/bin/bash

sudo pacman -S plymouth --noconfirm --needed

#Kernel Parameters - splash quiet
sudo sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet"/GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet splash"/' /etc/default/grub
sudo grub-mkconfig -o /boot/grub/grub.cfg

# Mkinitcpio Hooks - plymouth
sudo sed -i 's/fsck/fsck\ plymouth/' /etc/mkinitcpio.conf
sudo mkinitcpio -p linux

#https://github.com/adi1090x/plymouth-themes
paru -S plymouth-theme-abstract-ring-git plymouth-theme-circle-git plymouth-theme-circle-flow-git plymouth-theme-colorful-loop-git plymouth-theme-cuts-git plymouth-theme-cuts-alt-git plymouth-theme-liquid-git plymouth-theme-loader-2-git plymouth-theme-loader-alt-git  plymouth-theme-motion-git plymouth-theme-polaroid-git plymouth-theme-rings-2-git plymouth-theme-sphere-git plymouth-theme-spin-git plymouth-theme-splash-git plymouth-theme-square-git  --skipreview --sudoloop



