#!/bin/bash

drive=/dev/nvme0n1

sgdisk -Z  $drive

sgdisk -n 0:2048:+524288  -c 0:EFI          -t 0:0xef00 $drive
sgdisk -n 0:0:+104859648  -c 0:Windows      -t 0:0x0700 $drive
sgdisk -n 0:0:+838860800  -c 0:Personal     -t 0:0x8305 $drive
sgdisk -n 0:0:+52428800   -c 0:Arch         -t 0:0x8305 $drive
sgdisk -n 0:0:+16777216   -c 0:Swap         -t 0:0x8200 $drive
